### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by rpalenik** [in2group/package-crypto#8]
Hi,

I have run "mvn clean install" with success and  copied generated jars:
- in2-crypto-0.0.1.jar
- in2-crypto-package-0.0.1.jar
to " Ballerina/bre/lib" directory and also whole "in2" directory from "balo" to Ballerina/lib/repo.

During running ballerina build command I get following error:

Richard-Air:package-crypto rp$ ballerina --version
Ballerina 0.980.0
Richard-Air:package-crypto rp$ ballerina build testcrypto.bal
Compiling source
    testcrypto.bal
	could not find package in2/crypto:*

testcrypto.bal:
`import ballerina/io;
import in2/crypto;

function main(string[] args) {
  string stringToSign = "test";
  string signingKey = "test";

  string result = crypto:hmac(stringToSign, signingKey, crypto:SHA256);
  io:println(result);
}`
I am using MacOs version (0.980.0) but tried also linux and also 0.980.1 version with the same result.

It is my intention to write my own functions for AWS according to your great example. Have I missed something?

**Comment by mkasovic** [comment]
Hi Richard,

You should also try putting whole "in2" directory from "balo" to folder
".ballerina/repo" which is located in your user home directory. Also, you
don't need "in2-crypto-0.0.1.jar" in "Ballerina/bre/lib", you only need "
in2-crypto-package-0.0.1.jar".

So, to some up, you should have this layout:

   - $BALLERINA_HOME/bre/lib/in2-crypto-package-0.0.1.jar
   - $BALLERINA_HOME/lib/repo/in2/crypto/0.0.0/crypto.zip
   - $USER_HOME_FOLDER/.ballerina/repo/in2/crypto/0.0.0/crypto.zip


BR,
Marko

PS: I'm not sure why crypto.zip should be in both above mentioned
locations. Install scripts for native packages that are built by WSO2 team
have only $BALLERINA_HOME location for *.zip.

**Comment by mkasovic** [comment]
Hi Richard,

Two more things:

   1. Example from documentation for package-crypto has some errors.
   Signature of main method is wrong. It should be:
   function main (string... args) {
   2. Next week I'll try to install some WSO2 Ballerina native package (for
   example https://github.com/wso2-ballerina/package-redis) to see if I
   need to put redis.zip in user home folder. I'll post you results...


BR,
Marko

**Comment by rpalenik** [comment]
Hi Marko, many thanks it woks now. The problem probably was that I did not use install script(Mac privileges on Library folder) and did not know about $USER_HOME_FOLDER/.ballerina/repo/in2/crypto/0.0.0/crypto.zip necessity.

I would ultimately like to make AWS-SDK integration connection in the form of  ballerina connector but i am not able to do it due my little experience in  java, maven, etc... and current lack of good examples.

I tried your connector-azure-iotdevice (java) as an example but did not work as well probably due to heavy changes in ballerina introduced in each version. Do you think it could be similar problem as with package-crypto?

**Comment by mkasovic** [comment]
Hi Richard,

The connector-azure-iotdevice is built against Ballerina 0.964.0. Since then there were introduced some major changes in Ballerina runtime and this connector will not work with later versions. Instead of rewriting it to support newer versions of Ballerina I tried to implement pure Ballerina connector (only .bal files) that uses HTTPS instead of MQTT. If WSO2 team won't add support for SMTP to Ballerina by the end of august, I will probably rewrite connector-smtp to support newer versions of Ballerina.

BR,
Marko

**Comment by rpalenik** [comment]
Yes, I thought so. I am trying to find some implementation of java based connector that work:) so that I can hack it for my purpose. But maybe the one you mentioned (redis) could be good one.

Anyway many thanks, I will follow your progress and learn :)))

Richard



On 29 Jul 2018, at 20:39, Marko Kasović <notifications@github.com> wrote:

Hi Richard,

The connector-azure-iotdevice is built against Ballerina 0.964.0. Since then there were introduced some major changes in Ballerina runtime and this connector will not work with later versions. Instead of rewriting it to support newer versions of Ballerina I tried to implement pure Ballerina connector (only .bal files) that uses HTTPS instead of MQTT. If WSO2 team won't add support for SMTP to Ballerina by the end of august, I will probably rewrite connector-smtp to support newer versions of Ballerina.

BR,
Marko

**Comment by mkasovic** [comment]
This import problem is clearly Ballerina issue (https://github.com/ballerina-platform/ballerina-lang/issues/9777). So, unitl this issue is resolved I will update documentation and probably installation scripts.

**Comment by mkasovic** [comment]
This issue is resolved in Ballerina version 0.981.0, so that **crypto:hmac()** function now supports keyEncoding partamter.
